export const types = {
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
  FETCH_EMPLOYEES_SUCCEEDED: 'FETCH_EMPLOYEES_SUCCEEDED',
  FETCH_EMPLOYEES_FAILED: 'FETCH_EMPLOYEES_FAILED',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
  EMPLOYEE_UPDATE_SUCCEEDED: 'EMPLOYEE_UPDATE_SUCCEEDED',
  EMPLOYEE_UPDATE_FAILED: 'EMPLOYEE_UPDATE_FAILED',
}
